### ISSUE TITLE
Generating dart client code from a swagger ?

### ISSUE THREAD

**Issue by ghost** [stablekernel/open-api-dart#3]
I think that this repo does not do that but you might know.
I have a ton of swagger stuff and need to generate dart clients for dart angular and flutter to consume the swagger restful system.

Can you maybe point me in the right direction as I am guessing your developing in this area ?

Thanks in advance

**Comment by itsjoeconway** [comment]
Apologies for not seeing this before, I was not watching the repo. This does not generate the spec, see this repo: https://github.com/OpenAPITools/openapi-generator
